/* -*- mode: c++; indent-tabs-mode: nil -*- */
/** @file imagemagick-module.h imagemagick module header file */
/*
    Qore imagemagick module

    Copyright (C) 2026 Qore Technologies, s.r.o.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#ifndef _QORE_IMAGEMAGICK_MODULE_H
#define _QORE_IMAGEMAGICK_MODULE_H

#include <qore/Qore.h>
#include <qore/QoreSandboxManager.h>

#include <MagickWand/MagickWand.h>

// Forward declarations
class QoreMagickImage;
class QoreMagickDrawing;

// Hashdecl init functions (generated by QPP from QC_MagickImage.qpp)
DLLLOCAL TypedHashDecl* init_hashdecl_ImageInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_ImageResolutionInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_PointInfo(QoreNamespace& ns);

// Global hashdecl pointers (initialized in imagemagick-module.cpp)
extern const TypedHashDecl* hashdeclImageInfo;
extern const TypedHashDecl* hashdeclImageResolutionInfo;
extern const TypedHashDecl* hashdeclPointInfo;

// Namespace
extern QoreNamespace ImageMagickNs;

// Filter type constants for QPP
#define IM_FILTER_LANCZOS_VAL   ((int64)LanczosFilter)
#define IM_FILTER_MITCHELL_VAL  ((int64)MitchellFilter)
#define IM_FILTER_CATROM_VAL    ((int64)CatromFilter)
#define IM_FILTER_GAUSSIAN_VAL  ((int64)GaussianFilter)
#define IM_FILTER_BOX_VAL       ((int64)BoxFilter)
#define IM_FILTER_TRIANGLE_VAL  ((int64)TriangleFilter)
#define IM_FILTER_POINT_VAL     ((int64)PointFilter)
#define IM_FILTER_CUBIC_VAL     ((int64)CubicFilter)

#endif // _QORE_IMAGEMAGICK_MODULE_H
